---
- hosts: localhost
  connection: local
  become: true

  # Php is required for composer
  pre_tasks:
    - name: Install php
      package:
        state: present
        name:
          - php
          - php-curl
          - php-gd
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
      tags:
        - php

    - name: Remove apache because php installs it for some reason
      package:
        state: absent
        name: apache2
      tags:
        - php

  roles:
    - brave
    - node
    - rust
    - role: geerlingguy.docker
      become: true
      tags:
        - docker
    - role: geerlingguy.composer
      become: true
      tags:
        - php
    - role: gantsign.visual-studio-code
      tags:
        - vscode

  tasks:
    - name: install packages
      package:
        state: present
        name:
          - bat
          - flatpak
          - fzf
          - htop
          - peek
          - ranger
          - ripgrep
          - steam
          - tmux
          - vim
          - virt-manager
          - vlc
          - zsh

    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install Bottles
      flatpak:
        name: com.usebottles.bottles
        state: present
        method: system

    - name: Install GreenWithEnvy
      flatpak:
        name: com.leinardi.gwe
        state: present
        method: system

    - name: Install Heroic
      flatpak:
        name: com.heroicgameslauncher.hgl
        state: present
        method: system

    - name: Install Mattermost
      flatpak:
        name: com.mattermost.desktop
        state: present
        method: system

    - name: Install Neovim
      flatpak:
        name: io.neovim.nvim
        state: present
        method: system

    - name: Install OBS Studio
      flatpak:
        name: com.obsproject.Studio
        state: present
        method: system

    - name: Install OpenRGB
      flatpak:
        name: org.openrgb.OpenRGB
        state: present
        method: system

    - name: Install Signal
      flatpak:
        name: org.signal.Signal
        state: present
        method: system

    - name: Install Slack
      flatpak:
        name: com.slack.Slack
        state: present
        method: system

    - name: Install Spotify
      flatpak:
        name: com.spotify.Client
        state: present
        method: system

    - name: Install Zoom
      flatpak:
        name: us.zoom.Zoom
        state: present
        method: system

    - name: Install Discord
      package:
        name: discord

    - name: Install Blender
      package:
        name: blender

    - name: Install Lando
      apt:
        deb: 'https://files.devwithlando.io/lando-stable.deb'
        state: present

    - name: Install appimagelauncher
      import_tasks: tasks/appimagelauncher.yml
      become: true
      tags:
        - appimagelauncher

    - name: Install AWS Cli
      include: tasks/aws.yml
      become: true
      tags:
        - awscli

    - name: Install Joplin
      include: tasks/joplin.yml
      become: no
      tags:
        - joplin
