---
- hosts: localhost
  connection: local
  become: true

  roles:
    - brave
    - node
    - rust
  tasks:
    - name: install packages
      package:
        state: present
        name:
          - flatpak
          - htop
          - steam
          - vim
          - virt-manager

    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system

    - name: Install GreenWithEnvy
      flatpak:
        name: com.leinardi.gwe
        state: present
        method: system

    - name: Install Heroic
      flatpak:
        name: com.heroicgameslauncher.hgl
        state: present
        method: system

    - name: Install Mattermost
      flatpak:
        name: com.mattermost.desktop
        state: present
        method: system

    - name: Install Neovim
      flatpak:
        name: io.neovim.nvim
        state: present
        method: system

    - name: Install OBS Studio
      flatpak:
        name: com.obsproject.Studio
        state: present
        method: system

    - name: Install OpenRGB
      flatpak:
        name: org.openrgb.OpenRGB
        state: present
        method: system

    - name: Install Signal
      flatpak:
        name: org.signal.Signal
        state: present
        method: system

    - name: Install Slack
      flatpak:
        name: com.slack.Slack
        state: present
        method: system

    - name: Install Spotify
      flatpak:
        name: com.spotify.Client
        state: present
        method: system

    - name: Install Zoom
      flatpak:
        name: us.zoom.Zoom
        state: present
        method: system

    - name: Install zsh
      package:
        name: zsh

    - name: Install Discord
      package:
        name: discord

    - name: Install Blender
      package:
        name: blender

    - name: Install vlc
      package:
        name: vlc
