---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        state: present
        name:
          - flatpak
          - htop
          - steam
          - vim
          - virt-manager

    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install Bitwarden
      flatpak:
        state: present
        name: com.bitwarden.desktop
        method: user

    - name: Install GreenWithEnvy
      flatpak:
        name: com.leinardi.gwe
        state: present
        method: user

    - name: Install Mattermost
      flatpak:
        name: com.mattermost.desktop
        state: present
        method: user

    - name: Install Spotify
      flatpak:
        name: com.spotify.Client
        state: present
        method: user

    - name: Install Joplin
      flatpak:
        name: net.cozic.joplin_desktop
        state: present
        method: user

    - name: Install Signal
      flatpak:
        name: org.signal.Signal
        state: present
        method: user

    - name: Install Zoom
      flatpak:
        name: us.zoom.Zoom
        state: present
        method: user
