---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - flatpak
          - htop
          - vim
          - virt-manager

    - name: Add the flathub flatpak repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install flatpaks
      flatpak:
        name:
          - com.bitwarden.desktop
          - com.leinardi.gwe
          - com.mattermost.desktop
          - com.spotify.Client
          - net.cozic.joplin_desktop
          - org.signal.Signal
          - us.zoom.Zoom
        method: user
