---
- name: Ensure Brave dependencies are installed
  become: true
  apt:
    name:
      - curl
      - apt-transport-https
    state: present
  tags:
    - brave

- name: Download brave keyring
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags:
    - brave

- name: Brave Browser PPA setting
  become: true
  shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  tags:
    - brave

- name: Brave Browser apt installation
  become: true
  apt:
    update_cache: yes
    name: brave-browser
    state: present
  tags:
    - brave
