---
- name: Install node
  package:
    name: nodejs
    state: present

- name: Set fnm_dir
  set_fact:
    fnm_dir: "{{ lookup('env', 'HOME')}}/.fnm"
  tags:
    - fnm

- name: Check for fnm
  command: command -v fnm > /dev/null 2>&1
  register: fnm_exists
  ignore_errors: yes
  tags:
    - fnm
    - node

- name: Download fnm install script
  get_url:
    url: https://fnm.vercel.app/install
    dest: /tmp/fnm-install.sh
    mode: 0755
    force: yes
  when: fnm_exists.rc != 0
  register: fnm_script
  tags:
    - fnm
    - node

- name: Run fnm install script
  shell: /tmp/fnm-install.sh --install-dir {{ fnm_dir }}
  when: fnm_script.changed
  tags:
    - fnm
    - node

- name: Remove the fnm installer
  file:
    path: /tmp/fnm-install.sh
    state: absent
  tags:
    - fnm
    - node

- name: fnm use node lts
  shell:
    cmd: |
      eval "$(fnm env)"
      fnm use lts-latest --install-if-missing
  environment:
    PATH: '{{ fnm_dir }}:{{ ansible_env.PATH }}'
  tags:
    - fnm
    - node

# - name: Install npm global packages
#   npm:
#     name: npm
#     global: yes
  # loop:
  #   - npm
  #   - yarn
  #   - typescript
  # tags:
  #   - node
  #   - npm-global
